# Markdown settings
markdown:         kramdown
highlighter:      rouge

# Site settings
image:            /assets/img/logo.png
title:            Pentester Land
#tagline:          'Resources to learn penetration testing and bug bounty hunting'
tagline:          Offensive Infosec
description:      >
description:           >
  Offensive Infosec
#description:      >
#description:           >
#  Resources for penetration testers and bug bounty hunters
#
url:              https://pentester.land
baseurl:          
paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Build settings
include: ['_pages']

plugins_dir: _plugins

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
#version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
#github:
#  repo:             https://github.com/pentesterland/pentesterland.git
email:            "mailto:contact@pentester.land"
twitter:          "https://twitter.com/pentesterland"

disqus:
    shortname: pentester-land

google_analytics:	UA-114151690-1
